~pattern = (
    beat: (
        tone: \distorted,
        patterns: [
            \beat_x1,
            \beat_x2
        ]
    ),
    pad: (
        tone: \low_pass,
        patterns: [
            \pad,
            \pad_s
        ]
    ),
    bass: (
        tone: \flat,
        patterns: [
            \bass
        ]
    ),
    melody: (
        tone: \tight_metal,
        patterns: [
            \pulse,
            \melody
        ]
    )
)
